namespace LearningDotNet;

public interface ITask<out TResult>
{
    public TResult Perform();
}

public class EmailTask(string message, string recipient) : ITask<string>
{
    private string Message { get; } = message;
    private string Recipient { get; } = recipient;

    public string Perform()
    {
        return $"Email sent to: {Recipient}, with Message: {Message}";
    }
}

public class ReportTask(string reportName) : ITask<string>
{
    private string ReportName { get; } = reportName;

    public string Perform()
    {
        return $"Report {ReportName} generated by {nameof(EmailTask)}.";
    }
}

public class TaskProcessor<TTask, TResult>(TTask task) where TTask : ITask<TResult>
{
    private readonly TTask _task = task;

    public TResult Execute()
    {
        return _task.Perform();
    }
}
